[package]
name = "Lattice"
version = "0.5.0"
authors = ["Andrew <andrew@subarctic.org>"]
license = "MIT"
description = "A Simple Window Manager for Functional Reactive Programming"
edition = "2018"
readme = "README.md"
repository = "https://github.com/andrew-johnson-4/Lattice"
